First iteration after converting sds
See output: https://github.com/reutermj/sds

I started out with essentially this rules.md but without any of the conversion guidelines filled out. The initial prompt I gave was rules.md as part of the context and "follow the instructions in rules.md". Through the first iteration, it took me interjecting prompts to get it to follow best practices like using bzlmod instead of the workspace system, and it produced multiple test targets that were identical save for the name being slightly different. It did fix a couple of things on its own given bazel's errors and warnings such as loading `cc_library` and `cc_test` from rules.md.

The rules.md in this commit is pretty much the output of this first run. I reran the conversion with the first rules.md and it was able to translate the build with only a small hiccup in the BUILD file that it fixed on its own. I dont even know what the issue was because it was fixed before I needed to intervene.

Future improvements:
* Might want to prompt it to include buildifier as part of the process
* I wonder if there's merit to having a second iteration as part of the process that takes the output and evaluates it. Or maybe a second iteration that is to tell it to improve the build.

Insights:
* Good error messages from tooling seems helpful for these kinds of processes. Sometimes there would be an error like
```
ERROR: Skipping '//:sds_test': no such target '//:sds_test': target 'sds_test' not declared in package '' defined by /home/mark/data/CodeProjects/sds/BUILD.bazel
ERROR: no such target '//:sds_test': target 'sds_test' not declared in package '' defined by /home/mark/data/CodeProjects/sds/BUILD.bazel
INFO: Elapsed time: 0.029s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
ERROR: Couldn't start the build. Unable to run tests
```
But the issue was that the BUILD file had a minor syntax error. It would have been good for bazel to output that the build file had a syntax error because it took the agent running 2 other commands to figure it out